---
include:
- "**/*.rb"
- "/usr/local/bundle/gems/**/*.rb"
- vendor/**/*
- ".bundle/**/*"
exclude:
- spec/**/*
- test/**/*
require: # https://github.com/castwide/solargraph/issues/87
- actioncable
- actionmailer
- actionpack
- actionview
- activejob
- activemodel
- activerecord
- activestorage
- activesupport
- rails_helper
domains: []
reporters:
- rubocop
- require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
